name: Test and publish to npm

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*.*.*'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup build environment
        uses: ./.github/actions/setup

      - name: Check types
        run: npm run check

      - name: Run tests
        run: npm test

  release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    if: github.ref_type == 'tag'
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup build environment
        uses: ./.github/actions/setup

      - name: Build project
        run: npm run build

      - name: Extract release body from CHANGELOG.md
        run: awk 'f{if($0 ~ /^---/) exit; print} /^# /{f=1}' CHANGELOG.md | sed '/^[[:space:]]*$/d' > release-body.md

      - name: Publish to npm (beta)
        if: contains(github.ref, '-beta.')
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --provenance --access public --tag beta

      - name: Publish to npm (latest)
        if: ${{ !contains(github.ref, '-beta.') }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --provenance --access public

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: "${{ github.workspace }}/release-body.md"
